name: Run test workflows duplicate

on:
  push:
    branches:
      - CAT-780-enable-workflow-tests-for-prs

jobs:
  build:
    name: Install & Build
    runs-on: blacksmith-4vcpu-ubuntu-2204

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1



      - name: Use Node.js 22.x
        uses: useblacksmith/setup-node@v5
        with:
          node-version: 22.x

      - name: Setup corepack and pnpm
        run: |
          npm i -g corepack@0.31
          corepack enable

      - name: Setup build cache
        uses: useblacksmith/caching-for-turbo@v1

      - run: pnpm install --frozen-lockfile

      - name: Build Backend
        run: pnpm build

      - name: Cache build artifacts
        uses: useblacksmith/cache/save@v5
        with:
          path: ./packages/**/dist
          key: ${{ github.sha }}:workflow-tests

  run-test-workflows:
    name: Workflow Tests
    runs-on: blacksmith-2vcpu-ubuntu-2204
    needs: build
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Use Node.js 22.x
        uses: useblacksmith/setup-node@v5
        with:
          node-version: 22.x

      - name: Setup corepack and pnpm
        run: |
          npm i -g corepack@0.31
          corepack enable

      - name: Setup build cache
        uses: useblacksmith/caching-for-turbo@v1

      - run: pnpm install --frozen-lockfile

      - name: Restore cached build artifacts
        uses: useblacksmith/cache/restore@v5
        with:
          path: ./packages/**/dist
          key: ${{ github.sha }}:workflow-tests

      - name: Install OS dependencies
        run: |
          sudo apt update -y
          echo 'tzdata tzdata/Areas select Europe' | sudo debconf-set-selections
          echo 'tzdata tzdata/Zones/Europe select Paris' | sudo debconf-set-selections
          DEBIAN_FRONTEND="noninteractive" sudo apt-get install -y graphicsmagick

      - name: Checkout workflows repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: n8n-io/test-workflows
          path: test-workflows

      - name: Import credentials
        run: packages/cli/bin/n8n import:credentials --input=test-workflows/credentials.json
        env:
          N8N_ENCRYPTION_KEY: ${{secrets.ENCRYPTION_KEY}}

      - name: Import workflows
        run: packages/cli/bin/n8n import:workflow --separate --input=test-workflows/workflows
        env:
          N8N_ENCRYPTION_KEY: ${{secrets.ENCRYPTION_KEY}}

      - name: Copy static assets
        run: |
          cp assets/n8n-logo.png /tmp/n8n-logo.png
          cp assets/n8n-screenshot.png /tmp/n8n-screenshot.png
          cp test-workflows/testData/pdfs/*.pdf /tmp/

      - name: Run tests
        run: packages/cli/bin/n8n executeBatch --shallow --skipList=test-workflows/skipList.txt --githubWorkflow --shortOutput --concurrency=16
        id: tests
        env:
          N8N_ENCRYPTION_KEY: ${{secrets.ENCRYPTION_KEY}}
          SKIP_STATISTICS_EVENTS: true
          DB_SQLITE_POOL_SIZE: 4
